src/Rule/DeadMethodRule.php
While keeping requirement of phpstan in 1.10 range.
=> DeadMethodRule: allow analysis by phpstan 1.11

src/Collector/MethodCallCollector.php
Results in our case:
- Filesize of `resultCache.php` dropped from `384M` to `213M`
- RAM usage dropped from `20.14 GB` to `19.52 GB`
=> MethodCallCollector: emit data once per class

.github/dependabot.yml
We dont need stuff like https://github.com/shipmonk-rnd/dead-code-detector/pull/58
=> Dependabot: update only whitelisted packages

.github/dependabot.yml
Previous attempt #61 probably still does not work according to [logs](https://github.com/shipmonk-rnd/dead-code-detector/actions/runs/10700538117/job/29664498275):
> updater | 2024/09/04 11:14:58 WARN <job_879238385> Skipping update group for 'ci-tools' as it does not match any allowed dependencies.
=> Dependabot: try yet another only-whitelisted approach

README.md, phpstan.neon.dist, rules.neon, src/Collector/EntrypointCollector.php, src/Hierarchy/ClassHierarchy.php, src/Provider/DoctrineEntrypointProvider.php, src/Provider/EntrypointProvider.php, src/Provider/MethodBasedEntrypointProvider.php, src/Provider/MethodEntrypointProvider.php, src/Provider/NetteEntrypointProvider.php, src/Provider/PhpStanEntrypointProvider.php, src/Provider/PhpUnitEntrypointProvider.php, src/Provider/SimpleMethodEntrypointProvider.php, src/Provider/SymfonyEntrypointProvider.php, src/Provider/VendorEntrypointProvider.php, src/Rule/DeadMethodRule.php, tests/Rule/DeadMethodRuleTest.php, tests/Rule/data/DeadMethodRule/providers/phpunit.php
- This gains **performance boost at about ~20%** for our codebase
- This is because static reflection is very costy and main process need to build all the reflection (costy ast parsing) again (even though that was already done in collectors)
- In addition, PHPStan is not designed (performance-wise) for reflection heavy work in `Rule<CollectedDataNode>` as the reflection's underlying ast parser is doing ton of useless work, e.g. like parsing method bodies (such work is not useless in collectors/regular rules)
- Thus, using reflection in `Rule<CollectedDataNode>` is almost always bad idea
- Contains also BC break of changed `EntrypointProvider` interface. 
- This is needed to maintain the Symfony DIC constructors analysis precision. We do not have ClassHierarchy available in …
=> Remove all reflection work from main process

src/Collector/EntrypointCollector.php, src/Collector/MethodCallCollector.php
while the previous return type was correct, it did not explicitly state/protect you from someone changing the collector and make it return a empty array.
thats a major problem which can happen, and I want to make sure this error will not bite you, like it did in my projects.
for in-detail context see https://github.com/phpstan/phpstan/discussions/11701#discussioncomment-10660711
=> Make Collector return type more explicit

src/Provider/PhpUnitEntrypointProvider.php, tests/Rule/data/DeadMethodRule/providers/phpunit.php
_I expected this would break some tests but it does not_ 🤷🏾‍♀️ 
```php
abstract class TestCaseBase extends TestCase
{
abstract public static function providerTest(): array;
#[DataProvider('providerTest')]
public function testFoo(string|null $phpValue, string|null $serialized): void
{
}
}
final class SomeExtendingTest extends TestCaseBase
{
public static function providerTest(): array
{
return [];
}
}
```
Data providers in children classes are also valid entrypoints.
=> feat(phpunit): consider data providers in children classes as valid test entrypoints

README.md, phpcs.xml.dist, rules.neon, src/Collector/ClassDefinitionCollector.php, src/Collector/EntrypointCollector.php, src/Collector/MethodCallCollector.php, src/Crate/Call.php, src/Crate/Method.php, src/Crate/Visibility.php, src/Hierarchy/ClassHierarchy.php, src/Rule/DeadMethodRule.php, tests/AllServicesInConfigTest.php, tests/Rule/DeadMethodRuleTest.php, tests/Rule/data/DeadMethodRule/anonym.php, tests/Rule/data/DeadMethodRule/basic.php, tests/Rule/data/DeadMethodRule/callables.php, tests/Rule/data/DeadMethodRule/ctor-denied.php, tests/Rule/data/DeadMethodRule/ctor-private.php, tests/Rule/data/DeadMethodRule/cycles.php, tests/Rule/data/DeadMethodRule/dead-in-parent-1.php, tests/Rule/data/DeadMethodRule/first-class-callable.php, tests/Rule/data/DeadMethodRule/grouping/default.php, tests/Rule/data/DeadMethodRule/indirect-interface.php, tests/Rule/data/DeadMethodRule/magic.php, tests/Rule/data/DeadMethodRule/new-in-initializers.php, tests/Rule/data/DeadMethodRule/traits-23.php, tests/Rule/data/DeadMethodRule/traits-abstract-method.php
This allows to:
- detect dead cycles
- detect dead transitive calls
=> Call graph

README.md, rules.neon, src/Provider/ReflectionUsageProvider.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/providers/reflection.php
- Any constant or method accessed via `ReflectionClass` is detected as used
- e.g. `$reflection->getConstructor()`, `$reflection->getConstant('NAME')`, `$reflection->getMethods()`,
=> ReflectionUsageProvider

src/Provider/DoctrineUsageProvider.php, src/Provider/SymfonyUsageProvider.php, tests/Rule/data/providers/doctrine.php, tests/Rule/data/providers/symfony.php
With this, one can easily disable such provider and implement own child with adjusted logic while reusing most of the native logic.
=> Symfony & Doctrine: improve provider extendability

src/Provider/SymfonyUsageProvider.php, tests/Rule/data/providers/symfony.php
Previously, all methods of `EventSubscriberInterface` were marked as used. Not only those referenced in `getSubscribedEvents` + their transitive usages.
=> Symfony: precise detection of `EventSubscriberInterface::getSubscribedEvents`

src/Provider/DoctrineUsageProvider.php, tests/Rule/data/providers/doctrine.php
Previously, all methods of `EventSubscriber` were marked as used. Now only those referenced in `getSubscribedEvents` + their transitive usages.
=> Doctrine: precise `Doctrine\Common\EventSubscriber` detection

README.md, phpcs.xml.dist, rules.neon, src/Provider/SymfonyUsageProvider.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/providers/symfony.php, tests/Rule/data/providers/symfony/config/sftp.yaml
e.g. `!php/const Foo\Bar::BAZ`
=> Symfony: autodetect constants used in yamls 

src/Provider/SymfonyUsageProvider.php, tests/Rule/DeadCodeRuleTest.php
- `Configuration` class [no longer present since 2.0.2](https://github.com/phpstan/phpstan-symfony/releases/tag/2.0.2)
=> Symfony: fix DIC filepath for phpstan-symfony 2.0.2

src/Excluder/TestsUsageExcluder.php
Closes https://github.com/shipmonk-rnd/dead-code-detector/issues/152
[Docs](https://www.php.net/manual/en/function.realpath.php):
> The function realpath() will not work for a file which is inside a Phar as such path would be a virtual path, not a real one.
=> Cannot realpath phar paths

composer.json, composer.lock, src/Collector/MethodCallCollector.php, tests/Rule/data/methods/array-map-1.php, tests/Rule/data/methods/clone.php, tests/Rule/data/methods/parent-call-5.php
Possible since https://github.com/phpstan/phpstan-src/pull/3853
=> Utilize Type->isFinal for possible descendants detection

src/Collector/BufferedUsageCollector.php, src/Graph/CollectedUsage.php, src/Rule/DeadCodeRule.php, tests/Graph/SerializationTest.php
- Reduces result cache size
- Not as significant as https://github.com/phpstan/phpstan-src/pull/3879, but still worth it.
=> Optimize collected data size

README.md, rules.neon, src/Collector/ConstantFetchCollector.php, src/Collector/MethodCallCollector.php, src/Compatibility/BackwardCompatibilityChecker.php, src/Debug/DebugUsagePrinter.php, src/Excluder/MixedUsageExcluder.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/constants/mixed/untracked.php, tests/Rule/data/methods/mixed/untracked.php
- This improves visibility as **debug mode now shows the usages (and their exclusion)**. 
- Previously, one would see `No usages found` instead, which is not correct.
Breaking change:
```diff
parameters:
shipmonkDeadCode:
-         trackMixedAccess: false
+         usageExcluders:
+           usageOverMixed:
+               enabled: true
```
=> Replace `trackMixedAccess` config with `usageOverMixed` excluder

README.md, src/Graph/UsageOrigin.php, src/Provider/DoctrineUsageProvider.php, src/Provider/NetteUsageProvider.php, src/Provider/PhpStanUsageProvider.php, src/Provider/PhpUnitUsageProvider.php, src/Provider/ReflectionBasedMemberUsageProvider.php, src/Provider/SymfonyUsageProvider.php, src/Provider/VendorUsageProvider.php, src/Provider/VirtualUsage.php, src/Provider/VirtualUsageData.php, tests/AllServicesInConfigTest.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/debug/expected_output.txt
BC break for users of `ReflectionBasedMemberUsageProvider`, but with easy fix:
- `true => VirtualUsageData::withNote('why considered used')`
- `false => null`
=> Virtual usages always require note

.ecrc, README.md, rules.neon, src/Debug/DebugUsagePrinter.php, src/Error/BlackMember.php, src/Formatter/RemoveDeadCodeFormatter.php, src/Output/OutputEnhancer.php, src/Rule/DeadCodeRule.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/removing/no-namespace.output.txt, tests/Rule/data/removing/sample.output.txt, tests/Rule/data/removing/sample.php, tests/Rule/data/removing/sample.transformed.php
```txt
• Removed method UserFacade::deadMethod
! Excluded usage at tests/User/UserFacadeTest.php:241 left intact
```
=> Autoremove: warn about kept excluded usages

src/Collector/ConstantFetchCollector.php, src/Rule/DeadCodeRule.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/constants/descendant-1.php, tests/Rule/data/constants/descendant-2.php, tests/Rule/data/constants/descendant-3.php, tests/Rule/data/constants/descendant-4.php, tests/Rule/data/constants/traits-14.php
=> Improve descendant detection for const fetches

README.md
This allows to exclude truely **any** usage.
=> Readme: excluders are called after providers

src/Collector/ClassDefinitionCollector.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/other/report-lines.php, tests/Rule/data/providers/symfony.php
Minor **BC break for inline ignores when method had attribute** or some crazy-rare code-style:
```diff
-#[Deprecated] // @phpstan-ignore shipmonk.deadMethod
-public function someMethod(): void
+#[Deprecated]
+public function someMethod(): void // @phpstan-ignore shipmonk.deadMethod
```
=> Report dead method line at its name

src/Collector/ProvidedUsagesCollector.php
It fails e.g. when analysing phpstan-src:
```
Class 'PHPStan\ExtensionInstaller\GeneratedConfig' does not exist. 
It emitted usage of PHPStan\ExtensionInstaller\GeneratedConfig::PHPSTAN_VERSION_CONSTRAINT 
by ShipMonk\PHPStan\DeadCode\Provider\ReflectionUsageProvider 
for node 'PhpParser\Node\Expr\MethodCall' 
in '/home/honza/Development/phpstan-src/src/Command/CommandHelper.php' 
on line 303
```
=> Drop provided usage class existence validation

src/Excluder/TestsUsageExcluder.php, tests/AllServicesInConfigTest.php
Ensures no more mistakes like https://github.com/shipmonk-rnd/dead-code-detector/pull/202
=> Prevent DIC services to have ctors with defaults

README.md, rules.neon, src/Debug/DebugUsagePrinter.php, src/Provider/ApiPhpDocUsageProvider.php, src/Reflection/ReflectionHasOwnMemberTrait.php, src/Reflection/ReflectionHelper.php, tests/AllServicesInConfigTest.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/providers/api-phpdoc.php
Any public API of libs is dead by design (used only in tests), libs often use `@api` to mark such entrypoints. Most used by PHPStan itself.
=> Support libraries with `@api` phpdoc

src/Excluder/TestsUsageExcluder.php, tests/Rule/data/excluders/tests/src/code.php, tests/Rule/data/excluders/tests/tests/code.php
- We exclude only usages of src-defined classes. If we dont know the class, it should not be excluded.
=> TestsExcluder not to exclude mixed usages in tests

src/Provider/VendorUsageProvider.php, tests/Rule/data/providers/vendor.php
=> Detect also overridden vendor constants

README.md, src/Provider/SymfonyUsageProvider.php, tests/Rule/data/providers/symfony-gte71.php
AsMessageHandler Annotation https://github.com/symfony/symfony/blob/7.3/src/Symfony/Component/Messenger/Attribute/AsMessageHandler.php
gets now properly recognized as used
=> SymfonyUsageProvider: Add AsMessageHandler Annotation for Symfony
