src/Collector/MethodCallCollector.php
See https://github.com/phpstan/phpstan/issues/11286
Class wasn't imported and it caused phpstan to fail with an internal error
=> Fix exception in case of non-existent class

composer-dependency-analyser.php, composer.json, composer.lock
- https://github.com/shipmonk-rnd/composer-dependency-analyser
=> Initialize composer-dependency-analyser

src/Collector/ClassDefinitionCollector.php, src/Collector/MethodDefinitionCollector.php, src/Reflection/ClassHierarchy.php, src/Rule/DeadMethodRule.php, tests/Rule/data/DeadMethodRule/attribute.php, tests/Rule/data/DeadMethodRule/indirect-interface.php
Post analysis time drop in ShipMonk codebase:
- before: 154.4 s
- after: 76.96 s
=> Move most reflection work to collectors

README.md, composer.json, composer.lock, src/Collector/MethodDefinitionCollector.php, src/Provider/NetteEntrypointProvider.php, tests/Rule/DeadMethodRuleTest.php, tests/Rule/data/DeadMethodRule/providers/nette.php
Credit goes to @mabar: https://gist.github.com/mabar/2b10765d006f5c8a270d1ff482f72e9b
=> Nette entrypoint provider

.github/dependabot.yml
[Previous attempt is broken](https://github.com/shipmonk-rnd/dead-code-detector/pull/60#issuecomment-2328602670)
=> Dependabot: try different only-whitelisted approach

README.md, composer.json, composer.lock, src/Provider/SymfonyEntrypointProvider.php, tests/Rule/data/DeadMethodRule/providers/symfony.php
- Closes https://github.com/shipmonk-rnd/dead-code-detector/issues/86
- Closes https://github.com/shipmonk-rnd/dead-code-detector/issues/84
- Closes https://github.com/shipmonk-rnd/dead-code-detector/issues/93
=> Symfony: support `#[AsCommand]`, `#[AsController]`, Bundle children

README.md, collision-detector.json, composer.json, composer.lock, rules.neon, src/Formatter/RemoveDeadCodeFormatter.php, src/Rule/DeadMethodRule.php, src/Transformer/FileSystem.php, src/Transformer/RemoveMethodCodeTransformer.php, src/Transformer/RemoveMethodVisitor.php, tests/AllServicesInConfigTest.php, tests/Rule/DeadMethodRuleTest.php, tests/Rule/data/DeadMethodRule/removing/no-namespace.php, tests/Rule/data/DeadMethodRule/removing/no-namespace.transformed.php, tests/Rule/data/DeadMethodRule/removing/sample.php, tests/Rule/data/DeadMethodRule/removing/sample.transformed.php
How? Easy:
```
vendor/bin/phpstan analyse --error-format removeDeadCode
```
=> Autoremove dead code

src/Enum/MemberType.php, src/Graph/ClassConstantUsage.php, src/Graph/ClassMemberRef.php, src/Graph/ClassMemberUsage.php, src/Graph/ClassMethodUsage.php, src/Rule/DeadCodeRule.php, tests/AllServicesInConfigTest.php, tests/Graph/ClassMemberUsageTest.php
=> ClassMemberUsage: custom serialization logic

README.md
=> Readme: mention `EventSubscriberInterface::getSubscribedEvents`

tests/Rule/data/methods/traits-17.php
=> Fix a typo

src/Excluder/TestsUsageExcluder.php, tests/Rule/DeadCodeRuleTest.php
Closes https://github.com/shipmonk-rnd/dead-code-detector/issues/148
=> TestsExcluder: normalize provided paths

tests/Rule/DeadCodeRuleTest.php
Keep dataprovider testcases executable in PHPStorm:
=> Tests: generalize execution requirements api

src/Collector/BufferedUsageCollector.php, src/Collector/ConstantFetchCollector.php, src/Collector/MethodCallCollector.php, src/Collector/ProvidedUsagesCollector.php
Should not be needed once https://github.com/phpstan/phpstan-src/pull/3879 is merged.
=> Remove optimization of collector emits

composer.json, composer.lock, src/Provider/SymfonyUsageProvider.php, tests/Rule/data/providers/symfony.php
=> Symfony: support repositoryMethod in `#[UniqueEntity]`

src/Provider/SymfonyUsageProvider.php
Now we wont forget to add just another component.
=> Simplify symfony installation autodetect

README.md
Hopefully prevents confusions [like this](https://github.com/spaze/phpstan-disallowed-calls/pull/333#issuecomment-2884077722)
=> Readme: tests excluder wont disable whole analysis in tests

.github/workflows/e2e.yml
- Ref https://github.com/phpstan/phpstan-src/pull/3996
=> E2E: add phpstan/phpstan-src

README.md
Try prevent confusions like https://github.com/shipmonk-rnd/dead-code-detector/issues/209
=> Readme: whole codebase should be analysed

src/Provider/PhpUnitUsageProvider.php, tests/Rule/data/providers/phpunit.php
=> PHPUnit: support `#[DataProviderExternal]`

src/Rule/DeadCodeRule.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/methods/indirect-interface-9.php, tests/Rule/data/mixed-member/indirect-interface-9.php
=> Fix false positive with interface parent

src/Collector/ConstantFetchCollector.php, src/Collector/MethodCallCollector.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/constants/soft-final.php, tests/Rule/data/methods/soft-final.php
- Ref: https://github.com/6b7562617765726c6f73/PHP-CS-Fixer/actions/runs/16374739554/job/46271722803#step:12:19
=> Fix false positive when `@final` class is inherited

src/Provider/ApiPhpDocUsageProvider.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/providers/api-phpdoc.php
=> Support `@api` over enums and enum cases

src/Provider/ReflectionUsageProvider.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/debug/reflection.php, tests/Rule/data/providers/reflection-no-generics.php
- Only affects debug output as we ignore mixed over mixed anyway
=> ReflectionClass: do not emit mixed over mixed usages

src/Graph/UsageOrigin.php, tests/Rule/DeadCodeRuleTest.php, tests/Rule/data/methods/hooks-1.php
=> Add partial support for property hooks
